sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    access-key-id: LTAI5tFzLNVbe2wJqg8ikqDH
    access-key-secret: UYzASjkS5K7NcFpzCTYZBroTKrOqQk
    bucket-name: aliyun0410899050-sky-take-out
    endpoint: oss-cn-beijing.aliyuncs.com
  redis:
    host: localhost
    port: 6379
    database: 0
    password: 123456   #暂时没有设置密码
  wechat:
    appid: wx65039af2f74e039f
    secret: 9338c2bb4cfb603c8c9e24c3911b5e70
